inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
